// <auto-generated />
using System;
using AM.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AMContext))]
    [Migration("20221201204158_intialMigration2")]
    partial class intialMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationCore.Domain.Admission", b =>
                {
                    b.Property<int>("ChambresFk")
                        .HasColumnType("int");

                    b.Property<int>("PatientsFk")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdmission")
                        .HasColumnType("date");

                    b.Property<string>("ModifAdmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbJours")
                        .HasColumnType("int");

                    b.HasKey("ChambresFk", "PatientsFk", "DateAdmission");

                    b.HasIndex("PatientsFk");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("ApplicationCore.Domain.Chambre", b =>
                {
                    b.Property<int>("NumeroChambre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroChambre"));

                    b.Property<double>("Prix")
                        .HasColumnType("float");

                    b.Property<int>("typeChamber")
                        .HasColumnType("int");

                    b.HasKey("NumeroChambre");

                    b.ToTable("Chanbres");
                });

            modelBuilder.Entity("ApplicationCore.Domain.Clinique", b =>
                {
                    b.Property<int>("CliniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CliniqueId"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacite")
                        .HasColumnType("int");

                    b.Property<int>("NumTel")
                        .HasColumnType("int");

                    b.HasKey("CliniqueId");

                    b.ToTable("Cliniques");
                });

            modelBuilder.Entity("ApplicationCore.Domain.Patient", b =>
                {
                    b.Property<int>("NumDossier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumDossier"));

                    b.Property<string>("AdresseEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<int>("NumTel")
                        .HasColumnType("int");

                    b.HasKey("NumDossier");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ChambreClinique", b =>
                {
                    b.Property<int>("ChanbresNumeroChambre")
                        .HasColumnType("int");

                    b.Property<int>("CliniquesCliniqueId")
                        .HasColumnType("int");

                    b.HasKey("ChanbresNumeroChambre", "CliniquesCliniqueId");

                    b.HasIndex("CliniquesCliniqueId");

                    b.ToTable("ChambreClinique");
                });

            modelBuilder.Entity("ApplicationCore.Domain.Admission", b =>
                {
                    b.HasOne("ApplicationCore.Domain.Chambre", "Chambres")
                        .WithMany()
                        .HasForeignKey("ChambresFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Domain.Patient", "Patients")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientsFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chambres");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("ApplicationCore.Domain.Patient", b =>
                {
                    b.OwnsOne("ApplicationCore.Domain.NomComplet", "nomComplet", b1 =>
                        {
                            b1.Property<int>("PatientNumDossier")
                                .HasColumnType("int");

                            b1.Property<string>("Nom")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Prenom")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PatientNumDossier");

                            b1.ToTable("Patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientNumDossier");
                        });

                    b.Navigation("nomComplet")
                        .IsRequired();
                });

            modelBuilder.Entity("ChambreClinique", b =>
                {
                    b.HasOne("ApplicationCore.Domain.Chambre", null)
                        .WithMany()
                        .HasForeignKey("ChanbresNumeroChambre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Domain.Clinique", null)
                        .WithMany()
                        .HasForeignKey("CliniquesCliniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Domain.Patient", b =>
                {
                    b.Navigation("Admissions");
                });
#pragma warning restore 612, 618
        }
    }
}
